In [13]:
#imports 
import numpy as np
from sklearn.impute import SimpleImputer as s
from sklearn.impute import KNNImputer as knn

### Simple Imputer

In [7]:
imp=s(missing_values=np.nan,strategy="mean")
k=imp.fit_transform([[1,2,3],[np.nan,np.nan,2],[3,np.nan,np.nan]])
k   # Filled the nan values into mean of cols,
    #fit_transform  Apply SimpleImputer() to matrix and transform destinantion matrix;


array([[1. , 2. , 3. ],
       [2. , 2. , 2. ],
       [3. , 2. , 2.5]])

In [10]:
#similar method to fit and transform;
k1=imp.fit([[1,2,3],[np.nan,np.nan,2],[3,np.nan,np.nan]])
imp.transform([[1,2,3],[np.nan,np.nan,2],[3,np.nan,np.nan]])

array([[1. , 2. , 3. ],
       [2. , 2. , 2. ],
       [3. , 2. , 2.5]])

In [12]:
imp1=s(missing_values=np.nan,strategy="most_frequent")
k4=imp.fit_transform([[1,2,3],[np.nan,np.nan,2],[3,np.nan,np.nan]])
k4

array([[1. , 2. , 3. ],
       [2. , 2. , 2. ],
       [3. , 2. , 2.5]])

### KNN Imputer  (Fill Missing Values Using the nearest neighbour values mean )

In [14]:
X=[[3,4,5,6],[4,6,8,4],[np.nan,4,np.nan,6],[3,np.nan,4,np.nan]]
imputer=knn(n_neighbors=2)
imputer.fit_transform(X)

array([[3. , 4. , 5. , 6. ],
       [4. , 6. , 8. , 4. ],
       [3.5, 4. , 6.5, 6. ],
       [3. , 5. , 4. , 5. ]])