#### Numpy  Introductory Class

In [1]:
lst=[44.6,56,3]

In [45]:
import numpy as n

In [26]:
n_arr=n.array(lst)
type(n_arr)
n_arr.ndim

1

In [14]:
#numpy arrays are homogeneous
twod=[
    [1,2,4],
    [4,5,6],
    [5,6,7]
]
np_twod=n.array(twod)
np_twod.ndim


2

In [13]:
np_twod.shape

(3, 3)

In [21]:
#vectorised numpy operation
print(np_twod+1)

[[2 3 5]
 [5 6 7]
 [6 7 8]]


In [24]:
print(np_twod*3)

[[ 3  6 12]
 [12 15 18]
 [15 18 21]]


In [29]:
type(np_twod[0][0])

numpy.int32

In [42]:
q=n_arr+3.4

In [35]:
type(n[0])

numpy.float64

In [44]:
#Addition of two arrays where they are of different size /length  is not possible
n+np_twod

array([[49. , 61.4, 10.4],
       [52. , 64.4, 12.4],
       [53. , 65.4, 13.4]])

In [56]:
#creating a zero arrray with datatypes int/float64
a=n.zeros((3,3),dtype=int)
#creating ones array with datatypes as args
ones=n.ones((3,4),dtype=float)
#creating a fill with int with number to fill as parameter
fulls=n.full((4,5),5,dtype=int)

In [218]:
#creating a random matrix with range and size as limit

rand=n.random.randint(4,10,size=(3,4))
rand




array([[4, 9, 9, 5],
       [7, 8, 7, 9],
       [8, 6, 4, 5]])

In [229]:
new_rand=n.full((3,4),n.random.randint(10))


In [234]:
#generate number within range with lower limit inclusive and upperlimit excluded(l_lim,up_lim,step_val)
n.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

###### Boolean Indexing

In [257]:
k=n.arange(0,9)
k>5 #Return a  boolean array 
#Return the element in the array  limit index element where boolean operators used  filter 
k[(k>4) & (k<8)]*=-1 
k

array([ 0,  1,  2,  3,  4, -5, -6, -7,  8])

In [2]:
#statistic helper functions
#mean,median ,mode
l=n.arange(2,10)
print(n.mean(l))
print(n.median(l))
print(n.std(l)) #standard deviation 

NameError: name 'n' is not defined

In [4]:
#convert 1d array to twod or n-k dim to n dim ->reshape

l2 =l.reshape(2,4)
print(l2)

NameError: name 'l' is not defined

In [273]:
#convert n dim to 1 dim  ->flatten
print(l2.flatten())


[2 3 4 5 6 7 8 9]


In [3]:
#find max /min
print(l2.max(),l2.min())
#find max/min rowise axis=1
print(l2.min(axis=0))
#find max/min colwise axis =0
n.headstack
print(l2.max(axis=1))
#find max/min using axis parameter

NameError: name 'l2' is not defined