In [ ]:
import sys
#!{sys.executable} -m pip install summarytools
#!{sys.executable} -m pip install sketch
#pip install deepchecks -U --user
!{sys.executable}  -m pip install deepchecks 

In [ ]:
from summarytools import dfSummary

In [367]:
import seaborn as sns
import numpy as np
import pandas as pd

In [ ]:
titanic=sns.load_dataset('titanic')

In [ ]:
dfSummary(titanic)

### Playing with Numpy 

In [368]:
#create a len 10 int arr filled with 0
k=np.zeros(10,int).reshape(5,2)
#create 3x5 float arr
k1=np.ones((3,5),float)
#create 3x5 array fill with 3.14
k2=np.ones((3,5),float)*3.14
k21=np.full((3,5),3.14)

In [369]:
#create sequence in numpy

l=np.arange(2,10,2)
#create a evenly spaced seq 
np.linspace(1,5,6)
#create 3x3 matrix of randomly dist values
np.random.random((3,3))
#create 4x2 mat with normally dist rand val 
np.random.normal(0,1,(4,2))
#random ints in intervals

np.random.randint(0,10,(3,3))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [370]:
np.random.seed(0)
x1=np.random.randint(10,30,6)
x2=np.random.randint(10,30,(3,4))
x3=np.random.randint(10,30,(3,4,5))


In [371]:
x2

array([[19, 29, 28, 14],
       [16, 22, 11, 16],
       [17, 24, 27, 15]])

In [372]:
x2[0][0] 
x2[0,0]
x3[0,2:3]
x2[0,1::2]
x2[1::2]

array([[16, 22, 11, 16]])

In [373]:
x2[0][2::-1]


array([28, 29, 19])

In [374]:
#Array slices return views rather than copies 
#ie views can modify the original array
k=x2[0,1::2]
k[0]=5578
x2

array([[  19, 5578,   28,   14],
       [  16,   22,   11,   16],
       [  17,   24,   27,   15]])

In [375]:
#create copies of arrays
k=x2[0,::-1].copy()
k[0]=23
x2

array([[  19, 5578,   28,   14],
       [  16,   22,   11,   16],
       [  17,   24,   27,   15]])

In [376]:
x2[np.newaxis:]

array([[  19, 5578,   28,   14],
       [  16,   22,   11,   16],
       [  17,   24,   27,   15]])

In [377]:
m=x2[0:2]
np.vstack([m,k])


array([[  19, 5578,   28,   14],
       [  16,   22,   11,   16],
       [  23,   28, 5578,   19]])

In [378]:
#boolean indexing
c=np.arange(2,10)
c[(c>4) & (c<8)]*=-1
c

array([ 2,  3,  4, -5, -6, -7,  8,  9])

In [379]:
x2.max(axis=0)
x2.flatten()

array([  19, 5578,   28,   14,   16,   22,   11,   16,   17,   24,   27,
         15])

In [380]:
np.sum(x2)
np.sort(np.random.randint(0,100,(3,3)),axis=1)  #sort along row or column

array([[15, 52, 78],
       [20, 58, 99],
       [13, 23, 79]])

In [381]:
np.partition(x2,3,axis=1)

array([[  14,   19,   28, 5578],
       [  11,   16,   16,   22],
       [  15,   17,   24,   27]])

In [382]:
x2.diagonal()

array([19, 22, 27])

#### Playing  with pandas

In [383]:
dt=pd.Series(np.random.randint(0,10,3),index=['a','b','c'])
dt

a    5
b    5
c    0
dtype: int32

In [384]:
dt['b']

5

In [385]:
dictionary={'a1':1,'a2':2,'a3':23}
dp=pd.Series(dictionary)
dp['a1':'a2']

a1    1
a2    2
dtype: int64

In [386]:
pd.Series(dictionary,index=['a1']) #choose specific indices

a1    1
dtype: int64

In [387]:
tstdict={'Chennai':223,'Trichy':34,'Madurai':324,'Delhi':2324,'Mumbai':3232}
ar=pd.Series(tstdict)
df=pd.DataFrame({'val':ar})
df

val
Chennai   223
Trichy     34
Madurai   324
Delhi    2324
Mumbai   3232

In [388]:
df.index

Index(['Chennai', 'Trichy', 'Madurai', 'Delhi', 'Mumbai'], dtype='object')

In [389]:
pd.DataFrame(ar,columns=['val'])

val
Chennai   223
Trichy     34
Madurai   324
Delhi    2324
Mumbai   3232

In [390]:
pd.DataFrame([tstdict,dictionary])

Chennai  Trichy  Madurai   Delhi  Mumbai   a1   a2    a3
0    223.0    34.0    324.0  2324.0  3232.0  NaN  NaN   NaN
1      NaN     NaN      NaN     NaN     NaN  1.0  2.0  23.0

In [391]:
df.keys()

Index(['val'], dtype='object')

In [ ]:
from sklearn.datasets import load_digits
digits=load_digits(n_class=10)
import matplotlib.pyplot as plt
f,x=plt.subplots(8,8,figsize=(6,6))
for i,a in enumerate(x.flat):
    a.imshow(digits.images[i],cmap='binary')
    a.set(xticks=[],yticks=[])

In [392]:
df[(df['val']>200) & (df['val']<2000)]

val
Chennai  223
Madurai  324

In [393]:
d1={"name":['a','b','c'],"food":['apple','orange','banana']}
d2={"sample":['a','b','d'],"drink":["milk","coffee","tea"]}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)
df2.append(df2,ignore_index=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7060\2013225798.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



sample   drink
0      a    milk
1      b  coffee
2      d     tea
3      a    milk
4      b  coffee
5      d     tea

In [394]:
pd.merge(left=df1,right=df2,how='inner',left_on="name",right_on='sample')

name    food sample   drink
0    a   apple      a    milk
1    b  orange      b  coffee

In [395]:
df.loc[df.val>200,['val']] #fancy indexing

val
Chennai   223
Madurai   324
Delhi    2324
Mumbai   3232

In [396]:
dat={'a':1,'b':2,'c':np.nan,'d':3}

In [397]:
sp=pd.Series(dat)

ss=pd.DataFrame(sp)
ss.fillna(method='ffill')
ss['dd']=1
ss

0  dd
a  1.0   1
b  2.0   1
c  NaN   1
d  3.0   1

### Data Imputation

In [398]:
from sklearn.impute  import SimpleImputer as si
from sklearn.impute import KNNImputer as knn

In [399]:
imp=si(missing_values=np.nan,strategy='most_frequent')
x=np.array([[1,2,np.nan],[3,np.nan,3],[np.nan,3,5]])

x=x.reshape((3,3))
imp.fit_transform(x)

E:\anaconda\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning:

Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.



array([[1., 2., 3.],
       [3., 2., 3.],
       [1., 3., 5.]])

In [400]:
X=[[3,4,5,6],[4,6,8,4],[np.nan,4,np.nan,6],[3,np.nan,4,np.nan]]

In [401]:
ii=knn(n_neighbors=2)
x=ii.fit_transform(X)

#### Feature Scaling  


In [402]:
from sklearn.preprocessing import MaxAbsScaler,MinMaxScaler,StandardScaler

In [403]:
X1=MaxAbsScaler().fit_transform(x)
X1

array([[0.75      , 0.66666667, 0.625     , 1.        ],
       [1.        , 1.        , 1.        , 0.66666667],
       [0.875     , 0.66666667, 0.8125    , 1.        ],
       [0.75      , 0.83333333, 0.5       , 0.83333333]])

In [404]:
x2=MinMaxScaler().fit_transform(x)

x2

array([[0.   , 0.   , 0.25 , 1.   ],
       [1.   , 1.   , 1.   , 0.   ],
       [0.5  , 0.   , 0.625, 1.   ],
       [0.   , 0.5  , 0.   , 0.5  ]])

In [405]:
#standardization
StandardScaler().fit_transform(X1)

array([[-0.90453403, -0.90453403, -0.57735027,  0.90453403],
       [ 1.50755672,  1.50755672,  1.40213637, -1.50755672],
       [ 0.30151134, -0.90453403,  0.41239305,  0.90453403],
       [-0.90453403,  0.30151134, -1.23717915, -0.30151134]])